### ISSUE TITLE
Peer to peer code review: Tracy, Ellie, Ngozi

### ISSUE THREAD

**Issue by TracyMuso** [shyusu4/Berlin-Inno-Summit#2]
**Acknowledgements**
The project is very beautifully done! I love how the colors are contrasting.

**Suggested changes**

- Please increase the height of the top nav in the desktop version, it looks too small. 
- Please add the right semantic html tags where necessary( If there is a group of texts, use the article tag);
- Please add alternative texts to your images for better accessibility.

**Comment by shyusu4** [comment]
Hi @TracyMuso 👋 
Thank you for your constructive feedback, I appreciate it. I'll make sure to review my code.
