### ISSUE TITLE
Morning session: peer-to-peer code reviews: Alusine Jalloh, Elijah, Meshu Amare

### ISSUE THREAD

**Issue by Alusp** [shyusu4/Berlin-Inno-Summit#3]
### IN THIS PR

- Very nice design we suggest you add a view more button on the mobile version on speakers section.
- Nice use of semantic Tags we, suggest you stick to using one H1 in the index.html file
- We think you should consider the height of the Top Nav on the home page

**Comment by shyusu4** [comment]
Hey @Alusp!
Thanks for your comments, they're very helpful. I'll make sure to review my code and implement the suggestions you made.
